---
sidebar: sidebar 
permalink: trident-docker/multiple-instances-docker.html 
keywords: deploy, astra trident, docker, trident for docker, managed plugin, trident instances, alias 
summary: Se necesitan varias instancias de Astra Trident cuando se desean que varias configuraciones de almacenamiento estén disponibles de forma simultánea. La clave para varias instancias es darles nombres diferentes mediante la opción --alias con el plugin en contenedor, o la opción --volume-driver al crear instancias de Trident en el host. 
---
= Gestione varias instancias de Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se necesitan varias instancias de Trident cuando se desean que varias configuraciones de almacenamiento estén disponibles de forma simultánea. La clave para varias instancias es darles nombres diferentes mediante el `--alias` opción con el plugin en contenedor, o. `--volume-driver` Opción al crear una instancia de Trident en el host.



== Pasos para el complemento gestionado de Docker (versión 1.13/17.03 o posterior)

. Inicie la primera instancia que especifique un alias y un archivo de configuración.
+
[listing]
----
docker plugin install --grant-all-permissions --alias silver netapp/trident-plugin:21.07 config=silver.json
----
. Inicie la segunda instancia, especificando un alias y un archivo de configuración distintos.
+
[listing]
----
docker plugin install --grant-all-permissions --alias gold netapp/trident-plugin:21.07 config=gold.json
----
. Cree volúmenes que especifiquen el alias como el nombre del controlador.
+
Por ejemplo, para el volumen Gold:

+
[listing]
----
docker volume create -d gold --name ntapGold
----
+
Por ejemplo, en el caso del volumen Silver:

+
[listing]
----
docker volume create -d silver --name ntapSilver
----




== Pasos para tradicional (versión 1.12 o anterior)

. Inicie el plugin con una configuración NFS mediante un ID de controlador personalizado:
+
[listing]
----
sudo trident --volume-driver=netapp-nas --config=/path/to/config-nfs.json
----
. Inicie el plugin con una configuración iSCSI mediante un ID de controlador personalizado:
+
[listing]
----
sudo trident --volume-driver=netapp-san --config=/path/to/config-iscsi.json
----
. Aprovisione volúmenes Docker para cada instancia de controlador:
+
Por ejemplo, para NFS:

+
[listing]
----
docker volume create -d netapp-nas --name my_nfs_vol
----
+
Por ejemplo, para iSCSI:

+
[listing]
----
docker volume create -d netapp-san --name my_iscsi_vol
----

