---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, astra trident, methods, operator, tridentctl, helm 
summary: En función de la instalación de Astra Trident, hay varias opciones para desinstalarla. 
---
= Desinstale Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En función de la instalación de Astra Trident, hay varias opciones para desinstalarla.



== Desinstalar utilizando Helm

Si ha instalado Astra Trident mediante Helm, puede desinstalarlo mediante `helm uninstall`.

[listing]
----
#List the Helm release corresponding to the Astra Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== Desinstale mediante el operador Trident

Si ha instalado Astra Trident mediante el operador, puede desinstalarlo realizando una de las siguientes acciones:

* **Edición `TridentOrchestrator` Para establecer el indicador de desinstalación:** puede editar `TridentOrchestrator` y ajustar `spec.uninstall=true`. Edite el `TridentOrchestrator` CR y ajuste la `uninstall` marcar como se muestra a continuación:
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
Cuando la `uninstall` el indicador se establece en `true`, El operador Trident desinstala Trident, pero no quita el propio TridentOrchestrator. Debe limpiar el TridentOrchestrator y crear uno nuevo si desea volver a instalar Trident.

* **Eliminar `TridentOrchestrator`:** extrayendo el `TridentOrchestrator` CR utilizado para implementar Astra Trident, indica al operador que desinstale Trident. El operador procesa la eliminación de `TridentOrchestrator` Y procede a eliminar la implementación y el demonset de Astra Trident, con la eliminación de los pods de Trident que ha creado como parte de la instalación. Para eliminar completamente Astra Trident (incluidos los CRD que crea) y borrar la pizarra de forma efectiva, puede editar `TridentOrchestrator` para pasar la `wipeout` opción. Consulte el siguiente ejemplo:


[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"wipeout":["crds"],"uninstall":true}}'
----
Esto desinstala Astra Trident por completo y borra todos los metadatos relacionados con los back-ends y los volúmenes que gestiona. Las instalaciones posteriores se tratan como instalaciones frescas.


WARNING: Sólo debe considerar borrar los CRD al realizar una desinstalación completa. Esta acción no se puede deshacer. **No limpie los CRD a menos que esté buscando empezar y crear una nueva instalación de Astra Trident**.



== Desinstale mediante `tridentctl`

Ejecute el `uninstall` comando en `tridentctl` A continuación, se eliminan todos los recursos asociados con Astra Trident, excepto los CRD y los objetos relacionados, lo que facilita la ejecución del instalador de nuevo para actualizar a una versión más reciente.

[listing]
----
./tridentctl uninstall -n <namespace>
----
Para realizar una eliminación completa de Astra Trident, debe eliminar los finalizadores de los CRD creados por Astra Trident y eliminar los CRD.
