---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-operator.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: Puede actualizar fácilmente una instalación existente de Astra Trident mediante el operador. 
---
= Actualizar una instalación del operador Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar Astra Trident de forma manual o mediante Helm mediante el operador Trident. Puede actualizar desde una instalación de operador de Trident a otra instalación de operador de Trident o actualización desde un `tridentctl` Instalación en una versión de operador Trident. Revisar link:upgrade-trident.html#select-an-upgrade-method["Seleccione un método de actualización"] Antes de actualizar una instalación de operador Trident.



== Actualizar una instalación manual

Puede actualizar desde una instalación de operadores Trident en el ámbito del clúster a otra instalación del operador Trident en el ámbito del clúster. Todas las versiones 21.01 y posteriores de Astra Trident utilizan un operador con ámbito de clúster.


NOTE: Para actualizar desde Astra Trident que se instaló con el operador del ámbito de espacio de nombres (de la 20,07 a la 20,10), utiliza las instrucciones de actualización para link:../earlier-versions.html["la versión instalada"] De Astra Trident.

.Acerca de esta tarea
Trident proporciona un archivo de paquete que se puede utilizar para instalar el operador y crear objetos asociados para la versión de Kubernetes.

* Para los clústeres que ejecutan Kubernetes 1,24 o una versión anterior, utilice link:https://github.com/NetApp/trident/tree/stable/v23.10/deploy/bundle_pre_1_25.yaml["bundle_pre_1_25.yaml"^].
* Para los clústeres que ejecutan Kubernetes 1,25 o posterior, utilice link:https://github.com/NetApp/trident/tree/stable/v23.10/deploy/bundle_post_1_25.yaml["bundle_post_1_25.yaml"^].


.Antes de empezar
Asegúrese de que está utilizando un clúster de Kubernetes en ejecución link:../trident-get-started/requirements.html["Una versión de Kubernetes compatible"].

.Pasos
. Compruebe su versión de Astra Trident:
+
[listing]
----
./tridentctl -n trident version
----
. Elimine el operador Trident que se ha utilizado para instalar la instancia actual de Astra Trident. Por ejemplo, si va a actualizar desde 23,07, ejecute el siguiente comando:
+
[listing]
----
kubectl delete -f 23.07.0/trident-installer/deploy/<bundle.yaml> -n trident
----
. Si ha personalizado la instalación inicial mediante `TridentOrchestrator` atributos, puede editar `TridentOrchestrator` objeto para modificar los parámetros de instalación. Esto podría incluir cambios realizados para especificar registros de imágenes de Trident y CSI reflejados para el modo sin conexión, habilitar registros de depuración o especificar secretos de extracción de imágenes.
. Instale Astra Trident utilizando el archivo YAML de paquete correcto para su entorno, donde está _<bundle.yaml>_
`bundle_pre_1_25.yaml` o. `bundle_post_1_25.yaml` Según su versión de Kubernetes. Por ejemplo, si está instalando Astra Trident 23,10, ejecute el siguiente comando:
+
[listing]
----
kubectl create -f 23.10.0/trident-installer/deploy/<bundle.yaml> -n trident
----




== Actualizar una instalación Helm

Puede actualizar una instalación de Astra Trident Helm.


WARNING: Cuando actualice un clúster de Kubernetes de 1.24 a 1.25 o posterior que tenga instalado Astra Trident, debe actualizar Values.yaml para establecer `excludePodSecurityPolicy` para `true` o agregar `--set excludePodSecurityPolicy=true` para la `helm upgrade` comando antes de poder actualizar el clúster.

.Pasos
. Si usted link:../trident-get-started/kubernetes-deploy-helm.html#deploy-the-trident-operator-and-install-astra-trident-using-helm["Instalar Astra Trident mediante Helm"], usted puede utilizar `helm upgrade trident netapp-trident/trident-operator --version 23.10.0` para actualizar en un solo paso. Si no ha añadido el repositorio Helm o no puede utilizarlo para actualizar:
+
.. Descargue la versión más reciente de Astra Trident en link:https://github.com/NetApp/trident/releases/latest["La sección _Assets_ de GitHub"^].
.. Utilice la `helm upgrade` comando donde `trident-operator-23.10.0.tgz` refleja la versión a la que desea actualizar.
+
[listing]
----
helm upgrade <name> trident-operator-23.10.0.tgz
----
+

NOTE: Si establece opciones personalizadas durante la instalación inicial (como especificar registros privados reflejados para imágenes de Trident y CSI), agregue la `helm upgrade` comando que utiliza `--set` para asegurarse de que estas opciones están incluidas en el comando upgrade, de lo contrario, los valores se restablecerán a los valores predeterminados.



. Ejecución `helm list` para comprobar que la versión de la gráfica y de la aplicación se han actualizado. Ejecución `tridentctl logs` para revisar cualquier mensaje de depuración.




== Actualizar desde a. `tridentctl` Instalación para el operador Trident

Puede actualizarlo a la versión más reciente del operador de Trident desde un `tridentctl` instalación. Los back-ends y EVs existentes estarán disponibles automáticamente.


NOTE: Antes de cambiar entre los métodos de instalación, revise link:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["Moverse entre los métodos de instalación"]

.Pasos
. Descargue la última versión de Astra Trident.
+
[listing]
----
# Download the release required [23.10.0]
mkdir 23.10.0
cd 23.10.0
wget https://github.com/NetApp/trident/releases/download/v23.10.0/trident-installer-23.10.0.tar.gz
tar -xf trident-installer-23.10.0.tar.gz
cd trident-installer
----
. Cree el `tridentorchestrator` CRD del manifiesto.
+
[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----
. Despliegue el operador de ámbito de cluster en el mismo espacio de nombres.
+
[listing]
----
kubectl create -f deploy/<bundle-name.yaml>

serviceaccount/trident-operator created
clusterrole.rbac.authorization.k8s.io/trident-operator created
clusterrolebinding.rbac.authorization.k8s.io/trident-operator created
deployment.apps/trident-operator created
podsecuritypolicy.policy/tridentoperatorpods created

#Examine the pods in the Trident namespace
NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-79df798bdc-m79dc   6/6     Running   0          150d
trident-node-linux-xrst8              2/2     Running   0          150d
trident-operator-5574dbbc68-nthjv     1/1     Running   0          1m30s
----
. Cree un `TridentOrchestrator` CR para instalar Astra Trident.
+
[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident

kubectl create -f deploy/crds/tridentorchestrator_cr.yaml

#Examine the pods in the Trident namespace
NAME                                READY   STATUS    RESTARTS   AGE
trident-csi-79df798bdc-m79dc        6/6     Running   0          1m
trident-csi-xrst8                   2/2     Running   0          1m
trident-operator-5574dbbc68-nthjv   1/1     Running   0          5m41s
----
. Confirmar que Trident se ha actualizado a la versión prevista.
+
[listing]
----
kubectl describe torc trident | grep Message -A 3

Message:                Trident installed
Namespace:              trident
Status:                 Installed
Version:                v23.10.0
----

