---
sidebar: sidebar 
permalink: trident-use/anf-prep.html 
keywords: trident backend, azure netapp files, smb volumes, smb, windows, active directory, csi proxy 
summary: Antes de configurar el back-end ANF, debe asegurarse de que se cumplen los siguientes requisitos. 
---
= Prepárese para configurar un back-end de Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Antes de configurar el back-end de Azure NetApp Files, debe asegurarse de que se cumplan los siguientes requisitos.

Si es la primera vez que utiliza Azure NetApp Files o está en una nueva ubicación, se requiere alguna configuración inicial.

* Para configurar Azure NetApp Files y crear un volumen NFS, consulte https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-quickstart-set-up-account-create-volumes["Azure: Configure Azure NetApp Files y cree un volumen NFS"^].
* Para configurar Azure NetApp Files y añadir un volumen SMB, consulte: https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-create-volumes-smb["Azure: Cree un volumen de SMB para Azure NetApp Files"^].




== Requisitos

Para configurar y utilizar un https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files"^] back-end, necesita lo siguiente:

* `subscriptionID` Desde una suscripción de Azure con Azure NetApp Files habilitado.
* `tenantID`, `clientID`, y. `clientSecret` desde una link:https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal["Registro de aplicaciones"^] En Azure Active Directory con permisos suficientes para el servicio Azure NetApp Files. El registro de aplicaciones debe usar:
+
** El rol propietario o Colaborador link:https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Predefinidos por Azure"^]
** A. link:https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles-portal["Rol Colaborador personalizado"] en el nivel de suscripción (`assignableScopes`) Con los siguientes permisos que están limitados únicamente a lo que Astra Trident necesita. Después de crear el rol personalizado, link:https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal["Asigne el rol mediante el portal de Azure"^].
+
[source, JSON]
----
{
    "id": "/subscriptions/<subscription-id>/providers/Microsoft.Authorization/roleDefinitions/<role-definition-id>",
    "properties": {
        "roleName": "custom-role-with-limited-perms",
        "description": "custom role providing limited permissions",
        "assignableScopes": [
            "/subscriptions/<subscription-id>"
        ],
        "permissions": [
            {
                "actions": [
                    "Microsoft.NetApp/netAppAccounts/capacityPools/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/write",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/write",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/delete",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/write",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/delete",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/subvolumes/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/subvolumes/write",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/subvolumes/delete",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/subvolumes/GetMetadata/action",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/MountTargets/read",
                    "Microsoft.Network/virtualNetworks/read",
                    "Microsoft.Network/virtualNetworks/subnets/read",
                    "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/read",
                    "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/write",
                    "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/delete",
                    "Microsoft.Features/features/read",
                    "Microsoft.Features/operations/read",
                    "Microsoft.Features/providers/features/read",
                    "Microsoft.Features/providers/features/register/action",
                    "Microsoft.Features/providers/features/unregister/action",
                    "Microsoft.Features/subscriptionFeatureRegistrations/read"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}
----


* Azure `location` que contiene al menos uno link:https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-delegate-subnet["subred delegada"^]. A partir de Trident 22.01, la `location` parámetro es un campo obligatorio en el nivel superior del archivo de configuración del back-end. Los valores de ubicación especificados en los pools virtuales se ignoran.




== Requisitos adicionales para volúmenes SMB

* Un clúster de Kubernetes con un nodo de controladora Linux y al menos un nodo de trabajo de Windows que ejecuta Windows Server 2019. Astra Trident admite volúmenes de SMB montados en pods que se ejecutan solo en nodos de Windows.
* Al menos un secreto Astra Trident que contiene sus credenciales de Active Directory para que ANF pueda autenticarse en Active Directory. Generar secreto `smbcreds`:
+
[listing]
----
kubectl create secret generic smbcreds --from-literal username=user --from-literal password='password'
----
* Proxy CSI configurado como servicio de Windows. Para configurar un `csi-proxy`, consulte link:https://github.com/kubernetes-csi/csi-proxy["GitHub: Proxy CSI"^] o. link:https://github.com/Azure/aks-engine/blob/master/docs/topics/csi-proxy-windows.md["GitHub: Proxy CSI para Windows"^] Para nodos Kubernetes que se ejecutan en Windows.

