---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Obtenga información sobre la configuración de un back-end de ONTAP con controladores DE SAN de ONTAP. 
---
= Información general del controlador de SAN de ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Obtenga información sobre la configuración de un back-end de ONTAP con controladores SAN de ONTAP y Cloud Volumes ONTAP.



== Información sobre el controlador de SAN de ONTAP

Astra Trident proporciona los siguientes controladores de almacenamiento SAN para comunicarse con el clúster de ONTAP. Los modos de acceso admitidos son: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).


IMPORTANT: Si utiliza Astra Control para protección, recuperación y movilidad, lea <<Compatibilidad de controladores Astra Control>>.

[cols="2, 1, 1, 2, 2"]
|===
| Controlador | Protocolo | VolumeMode | Modos de acceso compatibles | Sistemas de archivos compatibles 


| `ontap-san`  a| 
ISCSI
 a| 
Bloque
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sin sistema de archivos; dispositivo de bloque sin procesar



| `ontap-san`  a| 
ISCSI
 a| 
Sistema de archivos
 a| 
RWO, RWOP

ROX y RWX no están disponibles en el modo de volumen del sistema de archivos.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san`  a| 
NVMe/TCP

Consulte <<Consideraciones adicionales para NVMe/TCP>>.
 a| 
Bloque
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sin sistema de archivos; dispositivo de bloque sin procesar



| `ontap-san`  a| 
NVMe/TCP

Consulte <<Consideraciones adicionales para NVMe/TCP>>.
 a| 
Sistema de archivos
 a| 
RWO, RWOP

ROX y RWX no están disponibles en el modo de volumen del sistema de archivos.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san-economy`  a| 
ISCSI
 a| 
Bloque
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sin sistema de archivos; dispositivo de bloque sin procesar



| `ontap-san-economy`  a| 
ISCSI
 a| 
Sistema de archivos
 a| 
RWO, RWOP

ROX y RWX no están disponibles en el modo de volumen del sistema de archivos.
 a| 
`xfs`, `ext3`, `ext4`

|===


=== Compatibilidad de controladores Astra Control

Astra Control proporciona una protección fluida, recuperación ante desastres y movilidad (mover volúmenes entre clústeres de Kubernetes) para los volúmenes creados con el `ontap-nas`, `ontap-nas-flexgroup`, y. `ontap-san` de windows Consulte link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Requisitos previos de replicación de Astra Control"^] para obtener más detalles.

[WARNING]
====
* Uso `ontap-san-economy` solo si se espera que el número de uso de volúmenes persistentes sea superior a link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Límites de volumen ONTAP compatibles"^].
* Uso `ontap-nas-economy` solo si se espera que el número de uso de volúmenes persistentes sea superior a link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Límites de volumen ONTAP compatibles"^] y la `ontap-san-economy` no se puede utilizar el conductor.
* No utilizar `ontap-nas-economy` si prevé la necesidad de protección de datos, recuperación ante desastres o movilidad.


====


== Permisos de usuario

Astra Trident espera que se ejecute como administrador de ONTAP o SVM, normalmente mediante el `admin` usuario del clúster o un `vsadmin` Usuario de SVM o un usuario con un nombre diferente que tenga el mismo rol. Para puestas en marcha de Amazon FSX para ONTAP de NetApp, Astra Trident espera que se ejecute como administrador de ONTAP o SVM, mediante el clúster `fsxadmin` usuario o un `vsadmin` Usuario de SVM o un usuario con un nombre diferente que tenga el mismo rol. La `fsxadmin` el usuario es un reemplazo limitado para el usuario administrador del clúster.


NOTE: Si utiliza la `limitAggregateUsage` parámetro, se necesitan permisos de administrador de clúster. Cuando se utiliza Amazon FSX para ONTAP de NetApp con Astra Trident, el `limitAggregateUsage` el parámetro no funciona con el `vsadmin` y.. `fsxadmin` cuentas de usuario. La operación de configuración generará un error si se especifica este parámetro.

Si bien es posible crear un rol más restrictivo dentro de ONTAP que puede utilizar un controlador Trident, no lo recomendamos. La mayoría de las nuevas versiones de Trident denominan API adicionales que se tendrían que tener en cuenta, por lo que las actualizaciones son complejas y propensas a errores.



== Consideraciones adicionales para NVMe/TCP

Astra Trident admite el protocolo de memoria no volátil rápida (NVMe) mediante el `ontap-san` controlador incluyendo:

* IPv6
* Snapshots y clones de volúmenes NVMe
* Cambiar el tamaño de un volumen NVMe
* Se importa un volumen NVMe que se creó fuera de Astra Trident para que Astra Trident gestione su ciclo de vida
* Multivía nativa de NVMe
* Cierre correcto o sin complicaciones de los K8s nodos (23,10)


Astra Trident no es compatible:

* DH-HMAC-CHAP que es compatible con NVMe de forma nativa
* Rutas múltiples del asignador de dispositivos (DM)
* Cifrado LUKS

