---
sidebar: sidebar 
permalink: trident-use/trident-fsx-prep.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: 'Puede integrar su sistema de archivos Amazon FSX para ONTAP de NetApp con Astra Trident para garantizar que los clústeres de Kubernetes que se ejecutan en Amazon Elastic Kubernetes Service (EKS) puedan aprovisionar volúmenes persistentes de bloques y archivos respaldados por ONTAP.' 
---
= Integración de Amazon FSX para ONTAP de NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede integrar su sistema de archivos Amazon FSX para ONTAP de NetApp con Astra Trident para garantizar que los clústeres de Kubernetes que se ejecutan en Amazon Elastic Kubernetes Service (EKS) puedan aprovisionar volúmenes persistentes de bloques y archivos respaldados por ONTAP.

.Antes de empezar
Además de link:../trident-get-started/requirements.html["Requisitos de Astra Trident"], Para integrar FSX para ONTAP con Astra Trident, necesita:

* Un clúster de Amazon EKS existente o un clúster de Kubernetes autogestionado con `kubectl` instalado.
* Un Amazon FSX existente para el sistema de archivos ONTAP de NetApp y una máquina virtual de almacenamiento (SVM) accesible desde los nodos de trabajo del clúster.
* Nodos de trabajo preparados para link:worker-node-prep.html["NFS o iSCSI"].
+

NOTE: Asegúrese de seguir los pasos de preparación de nodos necesarios para Amazon Linux y Ubuntu https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Imágenes de máquina de Amazon"^] (AMI) en función del tipo de IAM EKS.



.Requisitos adicionales para volúmenes SMB
* Un clúster de Kubernetes con un nodo de controladora Linux y al menos un nodo de trabajo de Windows que ejecuta Windows Server 2019. Astra Trident admite volúmenes de SMB montados en pods que se ejecutan solo en nodos de Windows.
* Al menos un secreto Astra Trident que contiene sus credenciales de Active Directory. Generar secreto `smbcreds`:
+
[listing]
----
kubectl create secret generic smbcreds --from-literal username=user --from-literal password='password'
----
* Proxy CSI configurado como servicio de Windows. Para configurar un `csi-proxy`, consulte link:https://github.com/kubernetes-csi/csi-proxy["GitHub: Proxy CSI"^] o. link:https://github.com/Azure/aks-engine/blob/master/docs/topics/csi-proxy-windows.md["GitHub: Proxy CSI para Windows"^] Para nodos Kubernetes que se ejecutan en Windows.




== Integración de controladores ONTAP SAN y NAS


WARNING: Si está configurando para volúmenes SMB, debe leer <<Prepárese para aprovisionar los volúmenes de SMB>> antes de crear el back-end.

.Pasos
. Ponga en marcha Astra Trident con una de las link:../trident-get-started/kubernetes-deploy.html["métodos de implementación"].
. Recoja el nombre de DNS del LIF de gestión de SVM. Por ejemplo, si utiliza la CLI de AWS, busque el `DNSName` entrada en `Endpoints` -> `Management` tras ejecutar el siguiente comando:
+
[listing]
----
aws fsx describe-storage-virtual-machines --region <file system region>
----
. Cree e instale certificados para link:ontap-nas-prep.html["Autenticación de back-end NAS"] o. link:ontap-san-prep.html["Autenticación de entorno de administración DE SAN"].
+

NOTE: Puede iniciar sesión en el sistema de archivos (por ejemplo, para instalar certificados) con SSH desde cualquier lugar que pueda llegar al sistema de archivos. Utilice la `fsxadmin` Usuario, la contraseña que configuró al crear el sistema de archivos y el nombre DNS de gestión desde `aws fsx describe-file-systems`.

. Cree un archivo de entorno de administración mediante sus certificados y el nombre DNS de la LIF de gestión, como se muestra en el ejemplo siguiente:
+
[role="tabbed-block"]
====
.YAML
--
[listing]
----
---
version: 1
storageDriverName: ontap-san
backendName: customBackendName
managementLIF: svm-XXXXXXXXXXXXXXXXX.fs-XXXXXXXXXXXXXXXXX.fsx.us-east-2.aws.internal
svm: svm01
clientCertificate: ZXR0ZXJwYXB...ICMgJ3BhcGVyc2
clientPrivateKey: vciwKIyAgZG...0cnksIGRlc2NyaX
trustedCACertificate: zcyBbaG...b3Igb3duIGNsYXNz
----
--
.JSON
--
[listing]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "backendName": "customBackendName",
  "managementLIF": "svm-XXXXXXXXXXXXXXXXX.fs-XXXXXXXXXXXXXXXXX.fsx.us-east-2.aws.internal",
  "svm": "svm01",
  "clientCertificate": "ZXR0ZXJwYXB...ICMgJ3BhcGVyc2",
  "clientPrivateKey": "vciwKIyAgZG...0cnksIGRlc2NyaX",
  "trustedCACertificate": "zcyBbaG...b3Igb3duIGNsYXNz"
 }

----
--
====
+
Para obtener información sobre la creación de back-ends, consulte estos enlaces:

+
** link:ontap-nas.html["Configurar un back-end con controladores NAS de ONTAP"]
** link:ontap-san.html["Configuración de un back-end con controladores SAN de ONTAP"]




.Resultados
Después de la implementación, puede crear una link:../trident-get-started/kubernetes-postdeployment.html["clase de almacenamiento, aprovisione un volumen y monte el volumen en un pod"].



== Prepárese para aprovisionar los volúmenes de SMB

Puede aprovisionar volúmenes SMB mediante el `ontap-nas` controlador. Antes de completar la tarea <<Integración de controladores ONTAP SAN y NAS>> complete los siguientes pasos.

.Pasos
. Cree recursos compartidos de SMB. Puede crear recursos compartidos de administrador de SMB de una de dos formas mediante el link:https://learn.microsoft.com/en-us/troubleshoot/windows-server/system-management-components/what-is-microsoft-management-console["Consola de administración de Microsoft"^] Complemento carpetas compartidas o uso de la CLI de ONTAP. Para crear los recursos compartidos de SMB mediante la CLI de ONTAP:
+
.. Si es necesario, cree la estructura de ruta de acceso de directorio para el recurso compartido.
+
La `vserver cifs share create` comando comprueba la ruta especificada en la opción -path durante la creación del recurso compartido. Si la ruta especificada no existe, el comando falla.

.. Cree un recurso compartido de SMB asociado con la SVM especificada:
+
[listing]
----
vserver cifs share create -vserver vserver_name -share-name share_name -path path [-share-properties share_properties,...] [other_attributes] [-comment text]
----
.. Compruebe que se ha creado el recurso compartido:
+
[listing]
----
vserver cifs share show -share-name share_name
----
+

NOTE: Consulte link:https://docs.netapp.com/us-en/ontap/smb-config/create-share-task.html["Cree un recurso compartido de SMB"^] para obtener todos los detalles.



. Al crear el back-end, debe configurar lo siguiente para especificar volúmenes de SMB. Para obtener información sobre todas las opciones de configuración del entorno de administración de ONTAP, consulte link:trident-fsx-examples.html["Opciones y ejemplos de configuración de FSX para ONTAP"].
+
[cols="3"]
|===
| Parámetro | Descripción | Ejemplo 


| `smbShare` | Nombre del recurso compartido SMB creado mediante Shared Folder Microsoft Management Console. Por ejemplo «smb-share». *Necesario para volúmenes SMB.* | `smb-share` 


| `nasType` | *Debe establecer en `smb`.* Si es nulo, el valor predeterminado es `nfs`. | `smb` 


| `securityStyle` | Estilo de seguridad para nuevos volúmenes. *Debe estar configurado en `ntfs` o. `mixed` Para volúmenes SMB.* | `ntfs` o. `mixed` Para volúmenes de SMB 


| `unixPermissions` | Modo para volúmenes nuevos. *Se debe dejar vacío para volúmenes SMB.* | "" 
|===

