---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows 
summary: 'El operador Trident le permite personalizar la manera en que se instala Astra Trident mediante los atributos del `TridentOrchestrator` espec.' 
---
= Personalice la instalación del operador de Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El operador Trident le permite personalizar la instalación de Astra Trident con los atributos del `TridentOrchestrator` espec. Si desea personalizar la instalación más allá de qué `TridentOrchestrator` los argumentos lo permiten, considere usar `tridentctl` Para generar manifiestos YAML personalizados y modificarlos según sea necesario.



== Descripción de los pods de la controladora y los pods de nodo

Astra Trident se ejecuta como un único pod de la controladora, más un pod de nodos en cada nodo de trabajo del clúster. El pod del nodo debe ejecutarse en cualquier host en el que desee montar potencialmente un volumen Astra Trident.

Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["selectores de nodos"^] y.. link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["toleraciones y tintes"^] se utilizan para restringir un pod para ejecutarse en un nodo concreto o preferido. Uso del "ControllerPlugin" y. `NodePlugin`, puede especificar restricciones y anulaciones.

* El complemento de la controladora se ocupa del aprovisionamiento y la gestión de volúmenes, como snapshots y redimensionamiento.
* El complemento de nodo se encarga de conectar el almacenamiento al nodo.




== Opciones de configuración


WARNING: `spec.namespace` se especifica en `TridentOrchestrator` Para indicar el espacio de nombres en el que está instalado Astra Trident. Este parámetro *no se puede actualizar después de instalar Astra Trident*. Al intentar hacerlo, se genera el `TridentOrchestrator` estado a cambiar a. `Failed`. Astra Trident no está pensado para la migración entre espacios de nombres.

Esta tabla detalla `TridentOrchestrator` atributos.

[cols="1,2,1"]
|===
| Parámetro | Descripción | Predeterminado 


| `namespace` | Espacio de nombres para instalar Astra Trident en | `"default"` 


| `debug` | Habilite la depuración para Astra Trident | `false` 


| `enableForceDetach` | `ontap-san` y.. `ontap-san-economy` solamente.

Funciona con cierre de nodos no controlado (NGN) de Kubernetes para conceder a los administradores de clústeres la capacidad de migrar de forma segura cargas de trabajo con volúmenes montados a nodos nuevos en caso de que un nodo se vuelva en mal estado. | `false` 


| `windows` | Ajuste a. `true` Permite la instalación en nodos de trabajo de Windows. | `false` 


| `cloudProvider` | Establezca en `"Azure"` Cuando se utilizan identidades gestionadas o una identidad de nube en un clúster de AKS. Establecer en «AWS» cuando se utiliza una identidad de nube en un clúster de EKS. | `""` 


| `cloudIdentity` | Defina la identidad de carga de trabajo («azure.workload.identity/client-id: Xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx») cuando utilice la identidad de cloud en un clúster de AKS. Establezca el rol de AWS IAM ('eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/astratrident-role) cuando utilice la identidad de la nube en un clúster de EKS. | `""` 


| `IPv6` | Instale Astra Trident sobre IPv6 | falso 


| `k8sTimeout` | Tiempo de espera para las operaciones de Kubernetes | `30sec` 


| `silenceAutosupport` | No envíe paquetes AutoSupport a NetApp
automáticamente | `false` 


| `autosupportImage` | La imagen contenedora para telemetría AutoSupport | `"netapp/trident-autosupport:24.06"` 


| `autosupportProxy` | La dirección/puerto de un proxy para enviar AutoSupport
Telemetría | `"http://proxy.example.com:8888"` 


| `uninstall` | Una Marca utilizada para desinstalar Astra Trident | `false` 


| `logFormat` | Formato de registro de Astra Trident para utilizar [text,json] | `"text"` 


| `tridentImage` | Imagen de Astra Trident para instalar | `"netapp/trident:24.06"` 


| `imageRegistry` | Ruta de acceso al registro interno, del formato
`<registry FQDN>[:port][/subpath]` | `"k8s.gcr.io/sig-storage"` (Kubernetes 1,19 o posterior)
o. `"quay.io/k8scsi"` 


| `kubeletDir` | Ruta al directorio kubelet del host | `"/var/lib/kubelet"` 


| `wipeout` | Lista de recursos que se van a suprimir para realizar una eliminación completa de
Astra Trident |  


| `imagePullSecrets` | Secretos para extraer imágenes de un registro interno |  


| `imagePullPolicy` | Establece la política de extracción de imágenes para el operador Trident. Valores válidos:
`Always` para tirar siempre de la imagen.
`IfNotPresent` para extraer la imagen solo si aún no existe en el nodo.
`Never` para no tirar nunca de la imagen. | `IfNotPresent` 


| `controllerPluginNodeSelector` | Selectores de nodos adicionales para POD.	Sigue el mismo formato que `pod.spec.nodeSelector`. | Sin valores predeterminados; opcional 


| `controllerPluginTolerations` | Anula la toleración de Kubernetes en pods. Sigue el mismo formato que `pod.spec.Tolerations`. | Sin valores predeterminados; opcional 


| `nodePluginNodeSelector` | Selectores de nodos adicionales para POD. Sigue el mismo formato que `pod.spec.nodeSelector`. | Sin valores predeterminados; opcional 


| `nodePluginTolerations` | Anula la toleración de Kubernetes en pods. Sigue el mismo formato que `pod.spec.Tolerations`. | Sin valores predeterminados; opcional 
|===

NOTE: Para obtener más información sobre el formato de los parámetros del pod, consulte link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Asignación de pods a nodos"^].



=== Detalles acerca de forzar separación

Forzar separación está disponible para `ontap-san` y.. `ontap-san-economy` solamente. Antes de habilitar la desconexión forzada, se debe habilitar el cierre de nodos (NGN) no controlado en el clúster de Kubernetes. Para obtener más información, consulte link:https://kubernetes.io/docs/concepts/architecture/nodes/#non-graceful-node-shutdown["Kubernetes: Cierre de nodo sin gracia"^].


WARNING: Dado que Astra Trident se basa en NGN de Kubernetes, no lo elimine `out-of-service` mantiene un nodo en mal estado hasta que se reprograman todas las cargas de trabajo no tolerables. La aplicación o eliminación imprudente de la contaminación puede poner en peligro la protección de datos de back-end.

Cuando el administrador del clúster de Kubernetes ha aplicado el `node.kubernetes.io/out-of-service=nodeshutdown:NoExecute` mancha al nodo y. `enableForceDetach` se establece en `true`, Astra Trident determinará el estado del nodo y:

. Cese el acceso de I/O back-end para los volúmenes montados en ese nodo.
. Marque el objeto de nodo de Astra Trident como `dirty` (no es seguro para las nuevas publicaciones).
+

NOTE: La controladora Trident rechazará nuevas solicitudes de volumen de publicación hasta que el nodo se vuelva a calificar (después de haberse marcado como `dirty`) Por el pod del nodo de Trident. No se aceptarán todas las cargas de trabajo programadas con una RVP montada (incluso después de que el nodo del clúster esté en buen estado y listo) hasta que Astra Trident pueda verificar el nodo `clean` (seguro para nuevas publicaciones).



Cuando se restaure el estado del nodo y se elimine el tinte, Astra Trident:

. Identifique y limpie las rutas publicadas obsoletas en el nodo.
. Si el nodo está en `cleanable` estado (se ha eliminado la contaminación de fuera de servicio y el nodo está en `Ready` estatal) Y todas las rutas obsoletas publicadas están limpias, Astra Trident reenviará el nodo como `clean` y permitir nuevos volúmenes publicados al nodo.




== Configuraciones de ejemplo

Puede utilizar los atributos en <<Opciones de configuración>> al definir `TridentOrchestrator` para personalizar la instalación.

.Configuración personalizada básica
[%collapsible]
====
Este es un ejemplo de una instalación personalizada básica.

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
====
.Selectores de nodos
[%collapsible]
====
Este ejemplo instala Astra Trident con selectores de nodos.

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====
.Nodos de trabajo de Windows
[%collapsible]
====
En este ejemplo se instala Astra Trident en un nodo de trabajo de Windows.

[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----
====
.Identidades administradas en un cluster AKS
[%collapsible]
====
En este ejemplo se instala Astra Trident para habilitar identidades gestionadas en un clúster de AKS.

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  cloudProvider: "Azure"
----
====
.Identidad de nube en un clúster AKS
[%collapsible]
====
En este ejemplo se instala Astra Trident para usarlo con una identidad de cloud en un clúster de AKS.

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  cloudProvider: "Azure"
  cloudIdentity: 'azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'

----
====
.Identidad de nube en un clúster de EKS
[%collapsible]
====
En este ejemplo se instala Astra Trident para usarlo con una identidad de cloud en un clúster de AKS.

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  cloudProvider: "AWS"
  cloudIdentity: "'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/astratrident-role'"
----
====