---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows 
summary: 'El operador Trident le permite personalizar la manera en que se instala Astra Trident mediante los atributos del `TridentOrchestrator` espec.' 
---
= Personalice la instalación del operador de Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El operador Trident le permite personalizar la instalación de Astra Trident con los atributos del `TridentOrchestrator` espec. Si desea personalizar la instalación más allá de qué `TridentOrchestrator` los argumentos lo permiten, considere usar `tridentctl` Para generar manifiestos YAML personalizados y modificarlos según sea necesario.



== Descripción de los pods de la controladora y los pods de nodo

Astra Trident se ejecuta como un único pod de la controladora, más un pod de nodos en cada nodo de trabajo del clúster. El pod del nodo debe ejecutarse en cualquier host en el que desee montar potencialmente un volumen Astra Trident.

Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["selectores de nodos"^] y.. link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["toleraciones y tintes"^] se utilizan para restringir un pod para ejecutarse en un nodo concreto o preferido. Uso del "ControllerPlugin" y. `NodePlugin`, puede especificar restricciones y anulaciones.

* El complemento de la controladora se ocupa del aprovisionamiento y la gestión de volúmenes, como snapshots y redimensionamiento.
* El complemento de nodo se encarga de conectar el almacenamiento al nodo.




== Opciones de configuración


WARNING: `spec.namespace` se especifica en `TridentOrchestrator` Para indicar el espacio de nombres en el que está instalado Astra Trident. Este parámetro *no se puede actualizar después de instalar Astra Trident*. Al intentar hacerlo, se genera el `TridentOrchestrator` estado a cambiar a. `Failed`. Astra Trident no está pensado para la migración entre espacios de nombres.

Esta tabla detalla `TridentOrchestrator` atributos.

[cols="3"]
|===
| Parámetro | Descripción | Predeterminado 


| `namespace` | Espacio de nombres para instalar Astra Trident en | "predeterminado" 


| `debug` | Habilite la depuración para Astra Trident | falso 


| `windows` | Ajuste a. `true` Permite la instalación en nodos de trabajo de Windows. | falso 


| `IPv6` | Instale Astra Trident sobre IPv6 | falso 


| `k8sTimeout` | Tiempo de espera para las operaciones de Kubernetes | 30 seg 


| `silenceAutosupport` | No envíe paquetes AutoSupport a NetApp automáticamente | falso 


| `enableNodePrep` | Administrar automáticamente las dependencias del nodo de trabajo (*BETA*) | falso 


| `autosupportImage` | La imagen contenedora para telemetría AutoSupport | "netapp/trident-autosupport:23.01" 


| `autosupportProxy` | La dirección/puerto de un proxy para enviar telemetría AutoSupport | "http://proxy.example.com:8888"[] 


| `uninstall` | Una Marca utilizada para desinstalar Astra Trident | falso 


| `logFormat` | Formato de registro de Astra Trident para utilizar [text,json] | "texto" 


| `tridentImage` | Imagen de Astra Trident para instalar | "netapp/trident:21.04" 


| `imageRegistry` | Ruta de acceso al registro interno, del formato
`<registry FQDN>[:port][/subpath]` | "k8s.gcr.io/sig-storage (k8s 1.19+) o quay.io/k8scsi" 


| `kubeletDir` | Ruta al directorio kubelet del host | “/var/lib/kubelet” 


| `wipeout` | Una lista de recursos para eliminar y realizar una eliminación completa de Astra Trident |  


| `imagePullSecrets` | Secretos para extraer imágenes de un registro interno |  


| `imagePullPolicy` | Establece la política de extracción de imágenes para el operador Trident. Valores válidos:
`Always` para tirar siempre de la imagen.
`IfNotPresent` para extraer la imagen solo si aún no existe en el nodo.
`Never` para no tirar nunca de la imagen. | `IfNotPresent` 


| `controllerPluginNodeSelector` | Selectores de nodos adicionales para POD. Sigue el mismo formato que pod.spec.nodeSelector. | Sin valores predeterminados; opcional 


| `controllerPluginTolerations` | Anula la toleración de Kubernetes en pods. Sigue el mismo formato que el de pod.spec.tolerancias. | Sin valores predeterminados; opcional 


| `nodePluginNodeSelector` | Selectores de nodos adicionales para POD. Sigue el mismo formato que pod.spec.nodeSelector. | Sin valores predeterminados; opcional 


| `nodePluginTolerations` | Anula la toleración de Kubernetes en pods. Sigue el mismo formato que el de pod.spec.tolerancias. | Sin valores predeterminados; opcional 
|===

NOTE: Para obtener más información sobre el formato de los parámetros del POD, consulte link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Asignación de pods a nodos"^].



== Configuraciones de ejemplo

Puede utilizar los atributos mencionados anteriormente al definir `TridentOrchestrator` para personalizar la instalación.

.Ejemplo 1: Configuración personalizada básica
[%collapsible%open]
====
Este es un ejemplo de una configuración personalizada básica.

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
====
.Ejemplo 2: Implementar con selectores de nodos
[%collapsible%open]
====
Este ejemplo ilustra cómo se puede implementar Trident con los selectores de nodos:

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====
.Ejemplo 3: Implementar en nodos de trabajo de Windows
[%collapsible%open]
====
Este ejemplo ilustra la implementación en un nodo de trabajo de Windows.

[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----
====