---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: Antes de instalar Astra Trident, debería revisar estos requisitos generales del sistema. Es posible que los back-ends específicos tengan requisitos adicionales. 
---
= Requisitos
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar Astra Trident, debería revisar estos requisitos generales del sistema. Es posible que los back-ends específicos tengan requisitos adicionales.



== Información crucial sobre Astra Trident 23.01

* Debe leer la siguiente información crítica sobre Astra Trident.*

.<strong> información bï¿½tico sobre Astra Tridbï¿½tico </strong>
[%collapsible%open]
====
* Kubernetes 1.26 ahora es compatible con Trident. Actualizar Trident antes de actualizar Kubernetes.
* Astra Trident cumple estrictamente el uso de la configuración de múltiples rutas en entornos SAN, con un valor recomendado de `find_multipaths: no` en el archivo multipath.conf.
+
Uso de la configuración sin multivía o el uso de `find_multipaths: yes` o. `find_multipaths: smart` el valor del archivo multipath.conf provocará fallos de montaje. Trident ha recomendado el uso de `find_multipaths: no` desde la versión 21.07.



====


== Front-ends compatibles (orquestadores)

Astra Trident admite varios orquestadores y motores de contenedor, incluidos los siguientes:

* Anthos en las instalaciones (VMware) y Anthos en bare metal 1.9, 1.10, 1.11
* Kubernetes 1.21 - 1.26
* Mirantis Kubernetes Engine 3.5
* OpenShift 4.9 - 4.12


El operador Trident es compatible con las siguientes versiones:

* Anthos en las instalaciones (VMware) y Anthos en bare metal 1.9, 1.10, 1.11
* Kubernetes 1.21 - 1.26
* OpenShift 4.9 - 4.12


Astra Trident también funciona con una gran cantidad de otras ofertas de Kubernetes completamente gestionadas y gestionadas, como Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Rancher y VMware Tanzu Portfolio.


WARNING: Antes de actualizar un clúster de Kubernetes de 1.24 a 1.25 o posterior que tenga instalado Astra Trident, consulte link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-based-operator-installation["Actualice la instalación de un operador basado en Helm"].



== Back-ends compatibles (almacenamiento)

Para utilizar Astra Trident, se necesitan uno o varios de los siguientes back-ends compatibles:

* Amazon FSX para ONTAP de NetApp
* Azure NetApp Files
* Cloud Volumes ONTAP
* Cloud Volumes Service para GCP
* FAS/AFF/Seleccione 9.5 o posterior
* Cabina All SAN de NetApp (ASA)
* Software HCI/Element de NetApp 11 o posterior




== Requisitos de funciones

La siguiente tabla resume las funciones disponibles con esta versión de Astra Trident y las versiones de Kubernetes compatible.

[cols="3"]
|===
| Función | La versión de Kubernetes | ¿Se requieren puertas de funciones? 


| CSI Trident  a| 
1.21 - 1.26
 a| 
No



| Snapshots de volumen  a| 
1.21 - 1.26
 a| 
No



| RVP desde snapshots de volumen  a| 
1.21 - 1.26
 a| 
No



| Cambio de tamaño del VP de iSCSI  a| 
1.21 - 1.26
 a| 
No



| CHAP bidireccional de ONTAP  a| 
1.21 - 1.26
 a| 
No



| Políticas de exportación dinámicas  a| 
1.21 - 1.26
 a| 
No



| Operador de Trident  a| 
1.21 - 1.26
 a| 
No



| Topología CSI  a| 
1.21 - 1.26
 a| 
No

|===


== Se probaron sistemas operativos host

Aunque Astra Trident no admite oficialmente sistemas operativos específicos, se sabe que lo siguiente es lo siguiente:

* Versiones de RedHat CoreOS (RHCOS) compatibles con OpenShift Container Platform
* RHEL 8 O POSTERIOR
* Ubuntu 22.04 o posterior
* Windows Server 2019


De forma predeterminada, Astra Trident se ejecuta en un contenedor y, por lo tanto, se ejecutará en cualquier trabajador de Linux. Sin embargo, estos trabajadores deben poder montar los volúmenes que ofrece Astra Trident con el cliente NFS o iniciador iSCSI estándar, en función de los back-ends que utilice.

La `tridentctl` Utility también se ejecuta en cualquiera de estas distribuciones de Linux.



== Configuración de hosts

Todos los nodos de trabajadores del clúster de Kubernetes deben poder montar los volúmenes que haya aprovisionado para los pods. Para preparar los nodos de trabajo, debe instalar las herramientas NFS o iSCSI según su selección de controlador.

link:../trident-use/worker-node-prep.html["Prepare el nodo de trabajo"]



== Configuración del sistema de almacenamiento

Es posible que Astra Trident requiera cambios en un sistema de almacenamiento antes de que una configuración de back-end pueda usarla.

link:../trident-use/backends.html["Configurar los back-ends"]



== Puertos Astra Trident

Astra Trident requiere acceso a puertos específicos para la comunicación.

link:../trident-reference/ports.html["Puertos Astra Trident"]



== Imágenes de contenedor y las versiones de Kubernetes correspondientes

Para instalaciones con problemas de conexión aérea, la siguiente lista es una referencia de las imágenes de contenedor necesarias para instalar Astra Trident. Utilice la `tridentctl images` comando para verificar la lista de imágenes de contenedor necesarias.

[cols="2"]
|===
| La versión de Kubernetes | Imagen de contenedor 


| 1.21.0  a| 
* netapp/trident:23.01.1
* netapp/trident-autosupport:23.01
* k8s.io/sig-storage/csi-aprovisionador:v3.4.0
* k8s.io/sig-storage/csi-attacher:v4.1.0
* k8s.io/sig-storage/csi-reszer:v1.7.0
* k8s.io/sig-storage/csi-snapshotter:v6.2.1
* k8s.io/sig-storage/csi-node-driver-registrador:v2.7.0
* netapp/operador especializado: 23.01.1 (opcional)




| v1.22.0  a| 
* netapp/trident:23.01.1
* netapp/trident-autosupport:23.01
* k8s.io/sig-storage/csi-aprovisionador:v3.4.0
* k8s.io/sig-storage/csi-attacher:v4.1.0
* k8s.io/sig-storage/csi-reszer:v1.7.0
* k8s.io/sig-storage/csi-snapshotter:v6.2.1
* k8s.io/sig-storage/csi-node-driver-registrador:v2.7.0
* netapp/operador especializado: 23.01.1 (opcional)




| v1.23.0  a| 
* netapp/trident:23.01.1
* netapp/trident-autosupport:23.01
* k8s.io/sig-storage/csi-aprovisionador:v3.4.0
* k8s.io/sig-storage/csi-attacher:v4.1.0
* k8s.io/sig-storage/csi-reszer:v1.7.0
* k8s.io/sig-storage/csi-snapshotter:v6.2.1
* k8s.io/sig-storage/csi-node-driver-registrador:v2.7.0
* netapp/operador especializado: 23.01.1 (opcional)




| v1.24.0  a| 
* netapp/trident:23.01.1
* netapp/trident-autosupport:23.01
* k8s.io/sig-storage/csi-aprovisionador:v3.4.0
* k8s.io/sig-storage/csi-attacher:v4.1.0
* k8s.io/sig-storage/csi-reszer:v1.7.0
* k8s.io/sig-storage/csi-snapshotter:v6.2.1
* k8s.io/sig-storage/csi-node-driver-registrador:v2.7.0
* netapp/operador especializado: 23.01.1 (opcional)




| v1.25.0  a| 
* netapp/trident:23.01.1
* netapp/trident-autosupport:23.01
* k8s.io/sig-storage/csi-aprovisionador:v3.4.0
* k8s.io/sig-storage/csi-attacher:v4.1.0
* k8s.io/sig-storage/csi-reszer:v1.7.0
* k8s.io/sig-storage/csi-snapshotter:v6.2.1
* k8s.io/sig-storage/csi-node-driver-registrador:v2.7.0
* netapp/operador especializado: 23.01.1 (opcional)




| v1.26.0  a| 
* netapp/trident:23.01.1
* netapp/trident-autosupport:23.01
* k8s.io/sig-storage/csi-aprovisionador:v3.4.0
* k8s.io/sig-storage/csi-attacher:v4.1.0
* k8s.io/sig-storage/csi-reszer:v1.7.0
* k8s.io/sig-storage/csi-snapshotter:v6.2.1
* k8s.io/sig-storage/csi-node-driver-registrador:v2.7.0
* netapp/operador especializado: 23.01.1 (opcional)


|===

NOTE: En la versión 1.21 de Kubernetes y versiones posteriores, utilice la validada `registry.k8s.gcr.io/sig-storage/csi-snapshotter:v6.x` la imagen sólo si la `v1` la versión sirve `volumesnapshots.snapshot.storage.k8s.gcr.io` CRD. Si la `v1beta1` La versión sirve al CRD con/sin el `v1` versión, utilice la validada `registry.k8s.gcr.io/sig-storage/csi-snapshotter:v3.x` imagen.
