---
sidebar: sidebar 
permalink: trident-reference/trident-cl.html 
keywords: command-line, options, logging, kubernetes, docker, ports 
summary: Astra Trident expone varias opciones de línea de comandos para Trident orchestrator y se comunica mediante determinados puertos. 
---
= Opciones de línea de comandos
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident expone varias opciones de línea de comandos para Trident orchestrator. Puede usar estas opciones para modificar la implementación.



== Registro

* `-debug`: Habilita la salida de depuración.
* `-loglevel <level>`: Establece el nivel de registro (debug, info, warn, error, fatal). Por defecto es info.




== Kubernetes

* `-k8s_pod`: Utilice esta opción o. `-k8s_api_server` Para habilitar la compatibilidad con Kubernetes. Al configurar esto, Trident usa las credenciales de cuenta del servicio de Kubernetes del pod para contactar con el servidor de API. Esto solo funciona cuando Trident se ejecuta como un pod en un clúster de Kubernetes con cuentas de servicio habilitadas.
* `-k8s_api_server <insecure-address:insecure-port>`: Utilice esta opción o. `-k8s_pod` Para habilitar la compatibilidad con Kubernetes. Cuando se especifica, Trident se conecta al servidor API de Kubernetes mediante el puerto y la dirección no seguras que se proporcionan. Esto permite que Trident se ponga en marcha fuera de un pod; sin embargo, solo admite conexiones no seguras con el servidor API. Para conectarse con seguridad, implemente Trident en un pod con el `-k8s_pod` opción.
* `-k8s_config_path <file>`: Necesario; debe especificar esta ruta de acceso a un archivo KubeConfig.




== Docker

* `-volume_driver <name>`: Nombre del controlador utilizado al registrar el complemento Docker. De forma predeterminada es `netapp`.
* `-driver_port <port-number>`: Escucha en este puerto en lugar de un socket de dominio UNIX.
* `-config <file>`: Necesario; debe especificar esta ruta de acceso a un archivo de configuración de back-end.




== DESCANSO

* `-address <ip-or-host>`: Especifica la dirección en la que debe escuchar el servidor REST de Trident. El valor predeterminado es localhost. Cuando se escucha en localhost y se ejecuta dentro de un pod Kubernetes, la interfaz REST no es accesible desde fuera del pod. Uso `-address ""` Para hacer que la interfaz DE REST sea accesible desde la dirección IP del pod.



CAUTION: La interfaz DE REST de Trident se puede configurar para escuchar y servir únicamente en 127.0.0.1 (para IPv4) o [::1] (para IPv6).

* `-port <port-number>`: Especifica el puerto en el que debe escuchar el servidor REST de Trident. El valor predeterminado es 8000.
* `-rest`: Activa la interfaz DE REPOSO. El valor predeterminado es TRUE.

